services:
  nmea-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/nmea-project
    ports:
      - "8080:8080"
    working_dir: /nmea-project
    stdin_open: true
    tty: true
    command: bash
    
